import kendari from "../assets/kendari.jpg"
import yogyakarta from "../assets/yogyakarta.jpg"
import bandung from "../assets/bandung.jpg"
import denpasar from "../assets/denpasar.jpg"
import makassar from "../assets/makassar.jpg"
import surabaya from "../assets/surabaya.jpg"
import malang from "../assets/malang.jpg"
import lombok from "../assets/lombok.jpg"
import amsterdam from "../assets/amsterdam.jpg"
import tokyo from "../assets/tokyo.jpg"
import seoul from "../assets/seoul.jpg"
import singapore from "../assets/singapore.jpg"
import kualaLumpur from "../assets/kuala-lumpur.jpg"
import osaka from "../assets/osaka.jpg"
import shanghai from "../assets/shanghai.jpg"
import melbourne from "../assets/melbourne.jpg"
import sydney from "../assets/sydney.jpg"

const indonesiaFlightList = [
    {
        id: 1,
        img: kendari,
        route: ["Jakarta", "Kendari"],
        area: "Domestic",
        date: "Sep",
        airline: "Quantum Air",
        transitNumber: 1,
        transitDuration: 2,
        transitCity: ["Makassar"],
        transitTime: [6, 8],
        departure: 4,
        arrival: 9,
        seat: "Economy",
        price: "1.345.000",
        list: "flights",
        facilities: ["Baggage", "In-flight meal"]
    },
    {
        id: 2,
        img: yogyakarta,
        route: ["Jakarta", "Yogyakarta"],
        area: "Domestic",
        date: "Sep",
        airline: "Nebula Airways",
        transitNumber: "Direct",
        transitDuration: 0,
        departure: 12,
        arrival: 13,
        seat: "Business",
        price: "2.675.000",
        list: "flights",
        facilities: ["Baggage", "In-flight meal", "Wifi", "Power/USB Port"]
    },
    {
        id: 3,
        img: bandung,
        route: ["Jakarta", "Bandung"],
        area: "Domestic",
        date: "Oct",
        airline: "Nebula Airways",
        transitNumber: "Direct",
        transitDuration: 0,
        departure: 11,
        arrival: 12,
        seat: "Economy",
        price: "1.254.000",
        list: "flights",
        facilities: ["Baggage", "Wifi"]
    },
    {
        id: 4,
        img: denpasar,
        route: ["Jakarta", "Bali"],
        area: "Domestic",
        date: "Aug",
        airline: "Quantum Air",
        transitNumber: "Direct",
        transitDuration: 0,
        departure: 14,
        arrival: 16,
        seat: "Economy",
        price: "1.095.000",
        list: "flights",
        facilities: ["Baggage", "Power/USB Port"]
    },
    {
        id: 5,
        img: makassar,
        route: ["Yogyakarta", "Makassar"],
        area: "Domestic",
        date: "Dec",
        airline: "Stellar Airlines",
        transitNumber: "Direct",
        transitDuration: 0,
        departure: 13,
        arrival: 15,
        seat: "Economy",
        price: "1.285.000",
        list: "flights",
        facilities: ["Baggage", "In-flight meal"]
    },
    {
        id: 6,
        img: bandung,
        route: ["Palembang", "Bandung"],
        area: "Domestic",
        date: "Nov",
        airline: "SkyWing",
        transitNumber: "Direct",
        transitDuration: 0,
        departure: 9,
        arrival: 11,
        seat: "Business",
        price: "2.265.000",
        list: "flights",
        facilities: ["Baggage", "In-flight meal", "Wifi", "Power/USB Port"]
    },
    {
        id: 7,
        img: surabaya,
        route: ["Jakarta", "Surabaya"],
        area: "Domestic",
        date: "Nov",
        airline: "SkyWing",
        transitNumber: "Direct",
        transitDuration: 0,
        departure: 19,
        arrival: 20,
        seat: "Business",
        price: "2.054.000",
        list: "flights",
        facilities: ["Baggage", "In-flight meal", "Wifi", "Power/USB Port"]
    },
    {
        id: 8,
        img: malang,
        route: ["Surabaya", "Malang"],
        area: "Domestic",
        date: "Sep",
        airline: "Thunderbird",
        transitNumber: "Direct",
        transitDuration: 0,
        departure: 21,
        arrival: 22,
        seat: "Economy",
        price: "1.065.000",
        list: "flights",
        facilities: ["Baggage", "Wifi"]
    },
    {
        id: 9,
        img: lombok,
        route: ["Jakarta", "Lombok"],
        area: "Domestic",
        date: "Oct",
        airline: "Quantum Air",
        transitNumber: 1,
        transitDuration: 3,
        transitCity: ["Makassar"],
        transitTime: [7, 10],
        departure: 5,
        arrival: 11,
        seat: "Economy",
        price: "965.000",
        list: "flights",
        facilities: ["Baggage", "Power/USB Port"]
    },
    {
        id: 10,
        img: yogyakarta,
        route: ["Denpasar", "Yogyakarta"],
        area: "Domestic",
        date: "Dec",
        airline: "SkyWing",
        transitNumber: "Direct",
        transitDuration: 0,
        departure: 7,
        arrival: 12,
        seat: "Business",
        price: "2.675.000",
        list: "flights",
        facilities: ["Baggage", "In-flight meal", "Wifi", "Power/USB Port"]
    }
]

const internationalFlightList = [
    {
        id: 11,
        img: amsterdam,
        route: ["Jakarta", "Amsterdam"],
        area: "International",
        date: "Dec",
        airline: "SkyWing",
        transitNumber: 1,
        transitDuration: 3,
        transitCity: ["Bangkok"],
        transitTime: [8, 11],
        departure: 4,
        arrival: 22,
        seat: "Business",
        price: "5.565.000",
        list: "flights",
        facilities: ["Baggage", "In-flight meal", "Wifi", "Power/USB Port"]
    },
    {
        id: 12,
        img: tokyo,
        route: ["Jakarta", "Tokyo"],
        area: "International",
        date: "Dec",
        airline: "Nebula Airways",
        transitNumber: 1,
        transitDuration: 3,
        transitCity: ["Kuala Lumpur"],
        transitTime: [10, 13],
        departure: 8,
        arrival: 16,
        seat: "Business",
        price: "5.765.000",
        list: "flights",
        facilities: ["Baggage", "In-flight meal", "Wifi", "Power/USB Port"]
    },
    {
        id: 13,
        img: seoul,
        route: ["Jakarta", "Seoul"],
        area: "International",
        date: "Nov",
        airline: "Stellar Airlines",
        transitNumber: 1,
        transitDuration: 6,
        transitCity: ["Kuala Lumpur"],
        transitTime: [14, 20],
        departure: 12,
        arrival: 23,
        seat: "Economy",
        price: "3.345.000",
        list: "flights",
        facilities: ["Baggage", "Wifi", "Power/USB Port"]
    },
    {
        id: 14,
        img: singapore,
        route: ["Denpasar", "Singapore"],
        area: "International",
        date: "Aug",
        airline: "Stellar Airlines",
        transitNumber: "Direct",
        transitDuration: 0,
        departure: 9,
        arrival: 11,
        seat: "Economy",
        price: "3.245.000",
        list: "flights",
        facilities: ["Baggage", "In-flight meal", "Power/USB Port"]
    },
    {
        id: 15,
        img: kualaLumpur,
        route: ["Jakarta", "Kuala Lumpur"],
        area: "International",
        date: "Oct",
        airline: "Elysian Airways",
        transitNumber: "Direct",
        transitDuration: 0,
        departure: 19,
        arrival: 21,
        seat: "Business",
        price: "5.124.000",
        list: "flights",
        facilities: ["Baggage", "In-flight meal", "Wifi", "Power/USB Port"]
    },
    {
        id: 16,
        img: osaka,
        route: ["Jakarta", "Osaka"],
        area: "International",
        date: "Sep",
        airline: "Nebula Airways",
        transitNumber: 1,
        transitDuration: 3,
        transitCity: ["Singapore"],
        transitTime: [20, 23],
        departure: 19,
        arrival: 1,
        seat: "Economy",
        price: "3.421.000",
        list: "flights",
        facilities: ["Baggage", "In-flight meal", "Wifi"]
    },
    {
        id: 17,
        img: singapore,
        route: ["Yogyakarta", "Singapore"],
        area: "International",
        date: "Aug",
        airline: "SkyWing",
        transitNumber: "Direct",
        transitDuration: 0,
        departure: 4,
        arrival: 6,
        seat: "Economy",
        price: "3.114.000",
        list: "flights",
        facilities: ["Baggage", "Wifi", "Power/USB Port"]
    },
    {
        id: 18,
        img: shanghai,
        route: ["Jakarta", "Shanghai"],
        area: "International",
        date: "Nov",
        airline: "Thunderbird",
        transitNumber: 1,
        transitDuration: 7,
        transitCity: ["Guangzhou"],
        transitTime: [8, 15],
        departure: 4,
        arrival: 16,
        seat: "Economy",
        price: "3.098.000",
        list: "flights",
        facilities: ["Baggage", "In-flight meal", "Power/USB Port"]
    },
    {
        id: 19,
        img: melbourne,
        route: ["Jakarta", "Melbourne"],
        area: "International",
        date: "Dec",
        airline: "Elysian Airways",
        transitNumber: 1,
        transitDuration: 4,
        transitCity: ["Denpasar"],
        transitTime: [20, 0],
        departure: 19,
        arrival: 3,
        seat: "Business",
        price: "5.876.000",
        list: "flights",
        facilities: ["Baggage", "In-flight meal", "Wifi", "Power/USB Port"]
    },
    {
        id: 20,
        img: sydney,
        route: ["Jakarta", "Sydney"],
        area: "International",
        date: "Dec",
        airline: "Thunderbird",
        transitNumber: 1,
        transitDuration: 5,
        transitCity: ["Kuala Lumpur"],
        transitTime: [15, 20],
        departure: 15,
        arrival: 23,
        seat: "Economy",
        price: "3.212.000",
        list: "flights",
        facilities: ["Baggage", "In-flight meal", "Wifi"]
    }
]

let flightsArray = [...indonesiaFlightList, ...internationalFlightList]

export { indonesiaFlightList, internationalFlightList, flightsArray }