export const kendariHotelList = [
    {
        id: 1,
        name: "Aurora Sky Hotel",
        img: require ("../images/hotel/hotel1.jpg"),
        stars: 4,
        rate: 4.2,
        review: 297,
        price: 77,
        city: "Kendari",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 2,
        name: "The Velvet Hotel",
        img: require ("../images/hotel/hotel2.jpg"),
        stars: 3,
        rate: 4,
        review: 277,
        price: 68,
        city: "Kendari",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 3,
        name: "Luminary Hotel",
        img: require ("../images/hotel/hotel3.jpg"),
        stars: 4,
        rate: 4.3,
        review: 277,
        price: 78,
        city: "Kendari",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 4,
        name: "Serenity Hotel",
        img: require ("../images/hotel/hotel4.jpg"),
        stars: 5,
        rate: 4.7,
        review: 333,
        price: 93,
        city: "Kendari",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 5,
        name: "Eclipse Grand Hotel",
        img: require ("../images/hotel/hotel5.jpg"),
        stars: 5,
        rate: 4.7,
        review: 345,
        price: 104,
        city: "Kendari",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 6,
        name: "Zenith Hotel",
        img: require ("../images/hotel/hotel6.jpg"),
        stars: 4,
        rate: 4.5,
        review: 296,
        price: 85,
        city: "Kendari",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Meeting Facilities"]
    },
    {
        id: 7,
        name: "Mystique Mano Hotel",
        img: require ("../images/hotel/hotel7.jpg"),
        stars: 4,
        rate: 4.3,
        review: 288,
        price: 83,
        city: "Kendari",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center"]
    },
    {
        id: 8,
        name: "The Oberoi Hotel",
        img: require ("../images/hotel/hotel8.jpg"),
        stars: 3,
        rate: 4.1,
        review: 277,
        price: 75,
        city: "Kendari",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Meeting Facilities"]
    },
    {
        id: 9,
        name: "Ayana Hotel",
        img: require ("../images/hotel/hotel9.jpg"),
        stars: 4,
        rate: 4.3,
        review: 286,
        price: 84,
        city: "Kendari",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 10,
        name: "Alila Uluwatu Hotel",
        img: require ("../images/hotel/hotel10.jpg"),
        stars: 3,
        rate: 4,
        review: 265,
        price: 70,
        city: "Kendari",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access"]
    }
]

export const jogjaHotelList = [
    {
        id: 11,
        name: "Celestial Treat Hotel",
        img: require ("../images/hotel/hotel11.jpg"),
        stars: 3,
        rate: 4.2,
        review: 307,
        price: 76,
        city: "Yogyakarta",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center"]
    },
    {
        id: 12,
        name: "Zenith Plaza Hotel",
        img: require ("../images/hotel/hotel12.jpg"),
        stars: 4,
        rate: 4.5,
        review: 282,
        price: 80,
        city: "Yogyakarta",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 13,
        name: "Saphire Sands Hotel",
        img: require ("../images/hotel/hotel13.jpg"),
        stars: 4,
        rate: 4.4,
        review: 312,
        price: 82,
        city: "Yogyakarta",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Meeting Facilities"]
    },
    {
        id: 14,
        name: "Avalon Haven Hotel",
        img: require ("../images/hotel/hotel14.jpg"),
        stars: 3,
        rate: 4.1,
        review: 290,
        price: 76,
        city: "Yogyakarta",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Meeting Facilities"]
    },
    {
        id: 15,
        name: "Syinjuku Hotel",
        img: require ("../images/hotel/hotel15.jpg"),
        stars: 3,
        rate: 4.2,
        review: 257,
        price: 77,
        city: "Yogyakarta",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Fitness Center"]
    },
    {
        id: 16,
        name: "Nova Skyline Hotel",
        img: require ("../images/hotel/hotel16.jpg"),
        stars: 5,
        rate: 4.8,
        review: 432,
        price: 98,
        city: "Yogyakarta",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 17,
        name: "Solstice Hotel",
        img: require ("../images/hotel/hotel17.jpg"),
        stars: 3,
        rate: 4.5,
        review: 276,
        price: 84,
        city: "Yogyakarta",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 18,
        name: "Enchanted Oasis Hotel",
        img: require ("../images/hotel/hotel18.jpg"),
        stars: 3,
        rate: 4.3,
        review: 267,
        price: 79,
        city: "Yogyakarta",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Meeting Facilities"]
    },
    {
        id: 19,
        name: "Vista Vista Hotel",
        img: require ("../images/hotel/hotel19.jpg"),
        stars: 4,
        rate: 4.4,
        review: 299,
        price: 88,
        city: "Yogyakarta",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center"]
    },
    {
        id: 20,
        name: "Luxe Mirage Hotel",
        img: require ("../images/hotel/hotel20.jpg"),
        stars: 5,
        rate: 4.8,
        review: 498,
        price: 102,
        city: "Yogyakarta",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    }
]

export const bandungHotelList = [
    {
        id: 21,
        name: "Azure Horizon Hotel",
        img: require ("../images/hotel/hotel21.jpg"),
        stars: 4,
        rate: 4.2,
        review: 400,
        price: 99,
        city: "Bandung",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 22,
        name: "The Ritz Hotel",
        img: require ("../images/hotel/hotel22.jpg"),
        stars: 4,
        rate: 4.3,
        review: 412,
        price: 105,
        city: "Bandung",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 23,
        name: "Cap EdenRoc Hotel",
        img: require ("../images/hotel/hotel23.jpg"),
        stars: 5,
        rate: 4.7,
        review: 478,
        price: 123,
        city: "Bandung",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 24,
        name: "Tranquil Haven Hotel",
        img: require ("../images/hotel/hotel24.jpg"),
        stars: 3,
        rate: 4.1,
        review: 378,
        price: 89,
        city: "Bandung",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center"]
    },
    {
        id: 25,
        name: "Costes Hotel",
        img: require ("../images/hotel/hotel25.jpg"),
        stars: 3,
        rate: 4.2,
        review: 387,
        price: 92,
        city: "Bandung",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Meeting Facilities"]
    },
    {
        id: 26,
        name: "Plaza Athenee Hotel",
        img: require ("../images/hotel/hotel26.jpg"),
        stars: 4,
        rate: 4.5,
        review: 420,
        price: 100,
        city: "Bandung",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center"]
    },
    {
        id: 27,
        name: "Opulent Elegance Hotel",
        img: require ("../images/hotel/hotel27.jpg"),
        stars: 5,
        rate: 4.6,
        review: 478,
        price: 124,
        city: "Bandung",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 28,
        name: "Lutetia Hotel",
        img: require ("../images/hotel/hotel28.jpg"),
        stars: 3,
        rate: 4.1,
        review: 366,
        price: 88,
        city: "Bandung",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Fitness Center"]
    },
    {
        id: 29,
        name: "Majestic Cannes Hotel",
        img: require ("../images/hotel/hotel29.jpg"),
        stars: 5,
        rate: 4.8,
        review: 452,
        price: 132,
        city: "Bandung",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 30,
        name: "Enigma Resev Hotel",
        img: require ("../images/hotel/hotel30.jpg"),
        stars: 4,
        rate: 4.3,
        review: 397,
        price: 104,
        city: "Bandung",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Meeting Facilities"]
    }
]

export const jakartaHotelList = [
    {
        id: 31,
        name: "Danieli Hotel",
        img: require ("../images/hotel/hotel31.jpg"),
        stars: 4,
        rate: 4.4,
        review: 389,
        price: 100,
        city: "Jakarta",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 32,
        name: "Belmond Splendido Hotel",
        img: require ("../images/hotel/hotel32.jpg"),
        stars: 3,
        rate: 4.1,
        review: 368,
        price: 94,
        city: "Jakarta",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access"]
    },
    {
        id: 33,
        name: "Crystal Haven Hotel",
        img: require ("../images/hotel/hotel33.jpg"),
        stars: 5,
        rate: 4.8,
        review: 412,
        price: 114,
        city: "Jakarta",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 34,
        name: "Hassler Hotel",
        img: require ("../images/hotel/hotel34.jpg"),
        stars: 3,
        rate: 4,
        review: 388,
        price: 92,
        city: "Jakarta",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 35,
        name: "Exquisite Bliss Hotel",
        img: require ("../images/hotel/hotel35.jpg"),
        stars: 5,
        rate: 4.7,
        review: 442,
        price: 124,
        city: "Jakarta",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 36,
        name: "Santa Caterina Hotel",
        img: require ("../images/hotel/hotel36.jpg"),
        stars: 4,
        rate: 4.4,
        review: 395,
        price: 103,
        city: "Jakarta",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center"]
    },
    {
        id: 37,
        name: "Castello Casole Hotel",
        img: require ("../images/hotel/hotel37.jpg"),
        stars: 3,
        rate: 4.2,
        review: 377,
        price: 91,
        city: "Jakarta",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Meeting Facilities"]
    },
    {
        id: 38,
        name: "Villa Cora Hotel",
        img: require ("../images/hotel/hotel38.jpg"),
        stars: 5,
        rate: 4.7,
        review: 476,
        price: 137,
        city: "Jakarta",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 39,
        name: "Harmonic Echoes Hotel",
        img: require ("../images/hotel/hotel39.jpg"),
        stars: 5,
        rate: 4.8,
        review: 467,
        price: 156,
        city: "Jakarta",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        id: 40,
        name: "Florence Lamassa Hotel",
        img: require ("../images/hotel/hotel40.jpg"),
        stars: 4,
        rate: 4.5,
        review: 386,
        price: 110,
        city: "Jakarta",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Fitness Center", "Meeting Facilities"]
    }
]

const baliHotelsList = [
    {
        name: "Enigma Lodge Hotel",
        img: require ("../images/hotel/hotel31.jpg"),
        stars: 4,
        rate: 4.3,
        review: 388,
        price: 103,
        city: "Bali",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        name: "Blissful Haven Hotel",
        img: require ("../images/hotel/hotel32.jpg"),
        stars: 3,
        rate: 4.1,
        review: 355,
        price: 98,
        city: "Bali",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Meeting Facilities"]
    },
    {
        name: "Eden Retreat Hotel",
        img: require ("../images/hotel/hotel33.jpg"),
        stars: 5,
        rate: 4.8,
        review: 456,
        price: 119,
        city: "Bali",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        name: "Luna Vista Hotel",
        img: require ("../images/hotel/hotel34.jpg"),
        stars: 3,
        rate: 4.2,
        review: 385,
        price: 97,
        city: "Bali",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access"]
    },
    {
        name: "Harmony Springs Hotel",
        img: require ("../images/hotel/hotel35.jpg"),
        stars: 5,
        rate: 4.7,
        review: 459,
        price: 122,
        city: "Bali",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        name: "Regal Heights Hotel",
        img: require ("../images/hotel/hotel36.jpg"),
        stars: 3,
        rate: 4.2,
        review: 388,
        price: 102,
        city: "Bali",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Fitness Center"]
    },
    {
        name: "Mirage Manor Hotel",
        img: require ("../images/hotel/hotel37.jpg"),
        stars: 3,
        rate: 4.2,
        review: 370,
        price: 97,
        city: "Bali",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access"]
    },
    {
        name: "Grand Paragon Hotel",
        img: require ("../images/hotel/hotel38.jpg"),
        stars: 4,
        rate: 4.5,
        review: 400,
        price: 114,
        city: "Bali",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Fitness Center", "Meeting Facilities"]
    },
    {
        name: "Serenade Hotel",
        img: require ("../images/hotel/hotel39.jpg"),
        stars: 5,
        rate: 4.9,
        review: 498,
        price: 152,
        city: "Bali",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center", "Meeting Facilities"]
    },
    {
        name: "Crystal Cove Hotel",
        img: require ("../images/hotel/hotel40.jpg"),
        stars: 4,
        rate: 4.4,
        review: 344,
        price: 108,
        city: "Bali",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator", "Wheelchair Access", "Fitness Center"]
    },
    {
        name: "Equinox Hotel",
        img: require ("../images/hotel/hotel31.jpg"),
        stars: 1,
        rate: 3.1,
        review: 211,
        price: 65,
        city: "Bali",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator"]
    },
    {
        name: "Majestic Peak Hotel",
        img: require ("../images/hotel/hotel32.jpg"),
        stars: 2,
        rate: 3.6,
        review: 220,
        price: 70,
        city: "Bali",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator"]
    },
    {
        name: "Serendipity Hotel",
        img: require ("../images/hotel/hotel31.jpg"),
        stars: 1,
        rate: 3,
        review: 201,
        price: 64,
        city: "Bali",
        list: "hotels",
        facilities: ["Wifi", "Parking", "Restaurant", "Elevator"]
    },
    {
        name: "Emporium Hotel",
        img: require ("../images/hotel/hotel32.jpg"),
        stars: 2,
        rate: 3.9,
        review: 234,
        price: 72,
        city: "Bali",
        list: "hotels",
        facilities: ["Wifi", "Swimming Pool", "Parking", "Restaurant", "Elevator"]
    }
]

export let hotelsArray = [...kendariHotelList, ...jogjaHotelList, ...bandungHotelList, ...jakartaHotelList, /*...baliHotelsList*/]